config/routes.rb
Fridaylunchspot::Application.routes.draw do
  get "spots/create"

  get "spots/destroy"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :restaurants
  resources :spots, only: [:create, :destroy]

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/restaurant.rb
# == Schema Information
#
# Table name: restaurants
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  address1   :string(255)
#  address2   :string(255)
#  city       :string(255)
#  state      :string(255)
#  zip        :string(255)
#  phone      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Restaurant < ActiveRecord::Base
  attr_accessible :address1, :address2, :city, :name, :phone, :state, :zip,
                  :approved

  has_many :spots, dependent: :destroy
  has_many :users, through: :spots, source: :user

  validates :name, presence: true, length: { maximum: 255 }
  validates :address1, presence: true, length: { maximum: 255 }
  validates :address2, length: { maximum: 255 }
  validates :city, presence: true, length: { maximum: 255 }
  validates :state, presence: true, length: { maximum: 255 }
  validates :zip, presence: true, length: { maximum: 255 }
  validates :phone, presence: true, length: { maximum: 255 }
end

app/models/spot.rb
class Spot < ActiveRecord::Base
  attr_accessible :restaurant_id

  belongs_to :user
  belongs_to :restaurant

  validates :user_id, presence: true
  validates :restaurant_id, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  first_name      :string(255)
#  last_name       :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  remember_token  :string(255)
#  admin           :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :password, 
                  :password_confirmation
  has_secure_password                

  has_many :spots, dependent: :destroy
  has_many :selected_spots, through: :spots, source: :restaurant

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :first_name, presence: true, length: { maximum: 35 }
  validates :last_name, presence: true, length: { maximum: 35 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def add_spot!(restaurant)
    spots.create!(restaurant_id: restaurant.id)
  end

  def remove_spot!(spot)
    spot.destroy
  end

  def has_spot?(restaurant)
    spots.find_by_restaurant_id(restaurant.id)
  end

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_filter :signed_in_user, only: [:index, :show, :new, :create, :edit, 
                                        :update, :destroy]
  before_filter :admin_user, only: [:edit, :update, :destroy]

  def index
    @restaurants = Restaurant.where(approved: true)
    @unapproved_restaurants = Restaurant.where(approved: false)
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(params[:restaurant])
    @restaurant.approved = false if !current_user.admin?

    if @restaurant.save
      flash[:success] = current_user.admin? ? "Restaurant created!" : 
            "Thanks for the submission! Our team will be reviewing it shortly."
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update_attributes(params[:restaurant])
      flash[:success] = "Restaurant updated!"
      redirect_to restaurants_path
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private
    
    def admin_user
      redirect_to(restaurants_path) unless current_user.admin?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email].downcase)
    if user && user.authenticate(params[:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_filter :signed_in_user

  def create
    @restaurant = Restaurant.find(params[:spot][:restaurant_id])
    current_user.add_spot!(@restaurant)
    respond_to do |format|
      format.html { redirect_to restaurant_path(@restaurant) }
      format.js
    end
  end

  def destroy
    @spot = Spot.find(params[:id])
    @restaurant = Restaurant.find(@spot.restaurant.id)
    current_user.remove_spot!(@spot)
    respond_to do |format|
      format.html { redirect_to restaurant_path(@restaurant) }
      format.js
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update]
  before_filter :correct_user,   only: [:edit, :update]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Wecome to fridaylunchspot!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_title)
    base_title = "fridaylunchspot"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div>&copy; 2013 fridaylunchspot.com</div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="navbar">
    <div class="navbar-inner">
      <div class="header container">
        <a class="brand" href="/">
          <img src="/assets/logo.png" alt="FridayLunchSpot">
        </a>
        <% if signed_in? %>
          <%= link_to "Restaurants", restaurants_path %>
          <%= link_to "Settings", edit_user_path(current_user) %>
          <%= link_to "Profile", user_path(current_user) %>
          <%= link_to "Sign out", signout_path, method: "delete" %>
        <% else %>
          <%= link_to "Sign in", signin_path, class: "signin pull-right" %>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %> 
  <div id="main" class="container">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/restaurants/_add_spot.html.erb
<%= form_for(current_user.spots.build(restaurant_id: @restaurant.id),
             remote: true) do |f| %>
  <div><%= f.hidden_field :restaurant_id %></div>
  <%= f.submit "Add spot", class: "btn btn-large btn-primary" %>
<% end %>

app/views/restaurants/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :address1, "Address" %>
<%= f.text_field :address1 %>
<%= f.text_field :address2 %>

<%= f.label :city %>
<%= f.text_field :city %>

<%= f.label :state %>
<%= f.text_field :state %>

<%= f.label :zip %>
<%= f.text_field :zip %>

<%= f.label :phone %>
<%= f.text_field :phone %>

<% if current_user.admin? %>
  <%= f.label :approved %>
  <%= f.check_box :approved %>
<% end %>

app/views/restaurants/_remove_spot.html.erb
<%= form_for(current_user.spots.find_by_restaurant_id(@restaurant.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Remove spot", class: "btn btn-large" %>
<% end %>

app/views/restaurants/_restaurant.html.erb
<div>
  <%= link_to restaurant.name, restaurant_path(restaurant) %> 
  <% if current_user.admin? %>
  <%= link_to "edit", edit_restaurant_path(restaurant) %>
  <%= link_to "delete", restaurant, method: :delete,
                                   data: { confirm: "You sure?" },
                                   title: restaurant.name %>
  <% end %>                                     
</div>

app/views/restaurants/_spot_form.html.erb
<div id="spot-form">
<% if current_user.has_spot?(@restaurant) %>
  <%= render 'remove_spot' %>
<% else %>
  <%= render 'add_spot' %>
<% end %>
</div>

app/views/restaurants/edit.html.erb
<% provide(:title, 'Edit restaurant') %>
<h1>Edit restaurant</h1>

<div class="row">
  <div class="span6">
    <%= form_for(@restaurant) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/restaurants/index.html.erb
<% provide(:title, 'Restaurants') %>

<%= link_to "Add a restaurant", new_restaurant_path %>

<h1>Restaurants</h1>
<%= render @restaurants %>

<% if @unapproved_restaurants.count > 0 %>
<h2>Unapproved Restaurants (<%= @unapproved_restaurants.count %>)</h1>
<%= render @unapproved_restaurants %>
<% end %>

app/views/restaurants/new.html.erb
<% provide(:title, 'Add a restaurant') %>
<h1>Add a restaurant</h1>

<div class="row">
  <div class="span6">
    <%= form_for(@restaurant) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Add restaurant", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/restaurants/show.html.erb
<% provide(:title, @restaurant.name) %>
<h1><%= @restaurant.name %></h1>
<%= render 'spot_form' if signed_in? %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/spots/create.js.erb
$("#spot-form").html("<%= escape_javascript(render('restaurants/remove_spot')) %>")

app/views/spots/destroy.js.erb
$("#spot-form").html("<%= escape_javascript(render('restaurants/add_spot')) %>")

app/views/static_pages/_user_home.html.erb
<h1>#TODO user homepage</h1>

app/views/static_pages/_visitor_home.html.erb
<h1>Looking for a place to eat at?</h1>
<div>
  <div class="home-section container">
    <h2>Pick your favorite spots</h2>
    <img src="http://placehold.it/600x400">
  </div>
</div>
<div class="light-gray">
  <div class="home-section container">
    <div class="row">
      <div class="span6">
        <h2>Share them with the world</h2>
        <img src="http://placehold.it/500x300">
      </div>
      <div class="span6">
        <h2>Find and follow other people</h2>
        <img src="http://placehold.it/500x300">
      </div>
    </div>
    <%= link_to "Sign up", signup_path, class: "signup" %>
  </div>
</div>
<div class="gray">
  <div class="home-section container">
    <h2>Check out</h2>
    <div class="row">
      <div class="span6">
        <h3>Dickson's Spots</h3>
        <img src="http://placehold.it/400x100">
      </div>
      <div class="span6">
        <h3>Andrew's Spots</h3>
        <img src="http://placehold.it/400x100">
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <%= render 'static_pages/user_home' %>
<% else %>
  <%= render 'static_pages/visitor_home' %>
<% end %> 

app/views/users/edit.html.erb
<% provide(:title, 'Settings') %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :first_name, "First Name" %>
      <%= f.text_field :first_name %>

      <%= f.label :last_name, "Last Name" %>
      <%= f.text_field :last_name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :first_name, "First Name" %>
      <%= f.text_field :first_name %>

      <%= f.label :last_name, "Last Name" %>
      <%= f.text_field :last_name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create Account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, "#{@user.first_name} #{@user.last_name}") %>
<h1><%= @user.first_name %> <%= @user.last_name %></h1>

<h2>My Spots</h2>
<% @user.selected_spots.each do |spot| %>
  <div><%= spot.name %></div>
<% end %>

<% if @user.selected_spots.count == 0 %>
  No spots
<% end %>